# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3292300b605eea32340f01abd5c982be1b434501d540443867c4acb8868c525ff2b630368c291fdaaccd4a580afad94ae3d1e4838461c60442b929047ff1640

test:
  secret_key_base: 1151d2ddf3937d8c8a8de18397afbea04154f92891aad75c71a762828fda07aaffc4de7a700a206ddb787c25a26e3f41bd05bfeea3df98c35f601bd7c1898eb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
